### ISSUE TITLE
Incompatible with current version of Create [Fabric 1.20.1]

### ISSUE THREAD

**Issue by SuperbNova11** [iGalaxyYT/create-origins#10]
The mod is incompatible with the newest version of create, currently 0.5.1-f-build.1417+mc1.20.1.

There is already an issue open but it is from a month ago and I just want to try and draw more attention.

**Comment by wiidotmom** [comment]
Fixed in https://github.com/wiidotmom/create-origins/commit/c04824549e7e136185a21997389e17723867edb1
