### ISSUE TITLE
0.5.1 Compatibility

### ISSUE THREAD

**Issue by RabbyDevs** [iGalaxyYT/create-origins#3]
Hey, here to let you know that Create for Fabric 0.5.1 (b) has come out, meaning this mod can be updated to 0.5.1, yippe!

**Comment by EzequielDM** [comment]
There are 2 open pull requests (blame me for the useless second one) implementing 0.5.1 compatibility.
#2 and #4 
Both contain forks that only implement these changes, if you wish you can compile from any of both forks.
Leaving this comment here so we don't get a third Pull Request lol

**Comment by RabbyDevs** [comment]
Nice, thanks for notifying me!

**Comment by wiidotmom** [comment]
Added in https://github.com/iGalaxyYT/create-origins/releases/tag/v1.2.0

See https://github.com/iGalaxyYT/create-origins/pull/4#issuecomment-1694773931 for my apology on not maintaining this mod for a while.
