### ISSUE TITLE
Netherite diving gear should bypass water vulnerability

### ISSUE THREAD

**Issue by V-lpen** [iGalaxyYT/create-origins#7]
So enderians and blazeborns can explore the oceans! :)

**Comment by noawx** [comment]
Or either the full netherite diving gear, like non-fire origins use the full netherite diving gear to dive into lava, waterphobic origins would use the full netherite diving gear to dive into water.

**Comment by wiidotmom** [comment]
I like the full netherite diving gear idea. I'll look into this.
