### ISSUE TITLE
[Universal - 1.20.1] Crash on startup

### ISSUE THREAD

**Issue by noawx** [iGalaxyYT/create-origins#9]
[Crash Log](https://mclo.gs/Ez1HQjR)

The game crashes when Create: Origins is enabled.

**Versions:**
Minecraft Version: 1.20.1
Quilt Loader: 0.25.0
QFAPI: 7.5.0+0.91.0-1.20.1
Create Fabric: 0.5.1-f-build.1417+mc1.20.1
Origins: 1.10.0
Create Origins: 1.2.1+1.20.1

No other mods were installed.

**Comment by mageowl** [comment]
I am getting this with fabric too.

**Comment by N0aW** [comment]
literally unplayable

**Comment by wiidotmom** [comment]
Fixed in https://github.com/wiidotmom/create-origins/commit/c04824549e7e136185a21997389e17723867edb1
